<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\File.png" />
    <None Remove="Images\Folder.png" />
    <None Remove="Images\FolderOpened.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ForestM8rix.Core\ForestM8rix.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\File.png" />
    <Resource Include="Images\Folder.png" />
    <Resource Include="Images\FolderOpened.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Nodes\" />
  </ItemGroup>

</Project>
